// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar configuration for ROS 2 textbook
  tutorialSidebar: [
    {
      type: 'category',
      label: 'ROS 2 Textbook',
      items: [
        'ros2/intro',
        'ros2/fundamentals',
        'ros2/rclpy-agents',
        'ros2/agent-controller-bridge',
        'ros2/urdf-humanoids',
        'ros2/testing-deployment',
      ],
    },
    {
      type: 'category',
      label: 'Module 2 — The Digital Twin (Simulation)',
      items: [
        'module-2/gazebo-physics-simulation',
        'module-2/sensors-environments',
      ],
    },
    {
      type: 'category',
      label: 'Module 3 — The AI-Robot Brain (NVIDIA Isaac)',
      items: [
        'module-3/nvidia-isaac-sim',
        'module-3/isaac-ros-navigation',
      ],
    },
    {
      type: 'category',
      label: 'Module 4 — Vision-Language-Action (VLA)',
      items: [
        'module-4/voice-to-action-systems',
        'module-4/llm-cognitive-planning',
      ],
    },
  ],
};

export default sidebars;
